events_lookup = {										
										
  -- Global										
  {	category= 'Global', 	sub_category= 'Crow aux', 	event_type= 'function', 	id= 'crow_event_trigger', 	name= 'Trigger', 	value_type= 'trigger', 				},
  {	category= 'Global', 	sub_category= 'Gen', 	event_type= 'function', 	id= 'event_chord_gen', 	name= 'Chord gen', 	value_type= 'trigger', 				},
  {	category= 'Global', 	sub_category= 'Gen', 	event_type= 'function', 	id= 'event_arp_gen', 	name= 'Arp gen', 	value_type= 'trigger', 				},
  {	category= 'Global', 	sub_category= 'Gen', 	event_type= 'function', 	id= 'event_gen', 	name= 'Ch+Ar gen', 	value_type= 'trigger', 				},
  {	category= 'Global', 	sub_category= 'Gen', 	event_type= 'param', 	id= 'chord_generator', 	name= 'Chord algo', 	value_type= 'inc, set', 				},
  {	category= 'Global', 	sub_category= 'Gen', 	event_type= 'param', 	id= 'arp_generator', 	name= 'Arp algo', 	value_type= 'inc, set', 				},
  {	category= 'Global', 	sub_category= 'Song', 	event_type= 'param', 	id= 'mode', 	name= 'Mode', 	value_type= 'set', 	formatter= 'mode_index_to_name', 			},
  {	category= 'Global', 	sub_category= 'Song', 	event_type= 'param', 	id= 'transpose', 	name= 'Key', 	value_type= 'inc, set', 	formatter= 'transpose_string', 			},
  {	category= 'Global', 	sub_category= 'Song', 	event_type= 'param', 	id= 'clock_tempo', 	name= 'Tempo', 	value_type= 'inc, set', 				},
  {	category= 'Global', 	sub_category= 'Song', 	event_type= 'param', 	id= 'crow_clock_index', 	name= 'Crow clock', 	value_type= 'inc, set', 	formatter= 'crow_clock_string', 	action= 'set_crow_clock', 		},
                      
  -- Chord										
  {	category= 'Chord', 	sub_category= 'Pattern', 	event_type= 'function', 	id= 'transpose_chord_pattern', 	name= 'Transpose', 	value_type= 'set', 				},
  {	category= 'Chord', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'chord_dest', 	name= 'Destination', 	value_type= 'set', 		action= 'update_menus', 		},
  {	category= 'Chord', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'chord_type', 	name= 'Chord type', 	value_type= 'set', 	formatter= 'chord_type', 			},
  {	category= 'Chord', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'chord_octave', 	name= 'Octave', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'chord_spread', 	name= 'Spread', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'chord_inversion', 	name= 'Inversion', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'chord_div_index', 	name= 'Step length', 	value_type= 'set', 	formatter= 'divisions_string', 	action= 'set_div', 	action_var= 'chord', 	},
  {	category= 'Chord', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'chord_duration_index', 	name= 'Duration', 	value_type= 'inc, set', 	formatter= 'divisions_string', 	action= 'set_duration', 	action_var= 'chord', 	},
  {	category= 'Chord', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'chord_pp_amp', 	name= 'Amp', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'Chord', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'chord_pp_cutoff', 	name= 'Cutoff', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'chord_pp_tracking', 	name= 'Fltr tracking', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'Chord', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'chord_pp_gain', 	name= 'Gain', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'chord_pp_pw', 	name= 'PW', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'Chord', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'chord_midi_out_port', 	name= 'Out port', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'chord_midi_ch', 	name= 'Channel', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'chord_midi_velocity', 	name= 'Velocity', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'chord_midi_cc_1_val', 	name= 'CC Mod', 	value_type= 'inc, set', 	formatter= 'neg_to_off', 			},
  {	category= 'Chord', 	sub_category= 'JF', 	event_type= 'param', 	id= 'chord_jf_amp', 	name= 'Amp', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	sub_category= 'Disting', 	event_type= 'param', 	id= 'chord_disting_velocity', 	name= 'Velocity', 	value_type= 'inc, set', 				},
                      
  -- Arp										
  {	category= 'Arp', 	sub_category= 'Pattern', 	event_type= 'function', 	id= 'shuffle_arp', 	name= 'Shuffle', 	value_type= 'trigger', 				},
  {	category= 'Arp', 	sub_category= 'Pattern', 	event_type= 'function', 	id= 'rotate_arp', 	name= 'Rotate', 	value_type= 'set', 				},
  {	category= 'Arp', 	sub_category= 'Pattern', 	event_type= 'function', 	id= 'transpose_arp_pattern', 	name= 'Transpose', 	value_type= 'set', 				},
  {	category= 'Arp', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'arp_dest', 	name= 'Destination', 	value_type= 'set', 		action= 'update_menus', 		},
  {	category= 'Arp', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'arp_chord_type', 	name= 'Chord type', 	value_type= 'set', 	formatter= 'chord_type', 			},
  {	category= 'Arp', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'arp_octave', 	name= 'Octave', 	value_type= 'inc, set', 				},
  {	category= 'Arp', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'arp_div_index', 	name= 'Step length', 	value_type= 'set', 	formatter= 'divisions_string', 	action= 'set_div', 	action_var= 'arp', 	},
  {	category= 'Arp', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'arp_duration_index', 	name= 'Duration', 	value_type= 'inc, set', 	formatter= 'divisions_string', 	action= 'set_duration', 	action_var= 'arp', 	},
  {	category= 'Arp', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'arp_mode', 	name= 'Mode', 	value_type= 'set', 				},
  {	category= 'Arp', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'arp_pp_amp', 	name= 'Amp', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'Arp', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'arp_pp_cutoff', 	name= 'Cutoff', 	value_type= 'inc, set', 				},
  {	category= 'Arp', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'arp_pp_tracking', 	name= 'Fltr tracking', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'Arp', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'arp_pp_gain', 	name= 'Gain', 	value_type= 'inc, set', 				},
  {	category= 'Arp', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'arp_pp_pw', 	name= 'PW', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'Arp', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'arp_midi_out_port', 	name= 'Out port', 	value_type= 'inc, set', 				},
  {	category= 'Arp', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'arp_midi_ch', 	name= 'Channel', 	value_type= 'inc, set', 				},
  {	category= 'Arp', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'arp_midi_velocity', 	name= 'Velocity', 	value_type= 'inc, set', 				},
  {	category= 'Arp', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'arp_midi_cc_1_val', 	name= 'CC Mod', 	value_type= 'inc, set', 	formatter= 'neg_to_off', 			},
  {	category= 'Arp', 	sub_category= 'Crow', 	event_type= 'param', 	id= 'arp_tr_env', 	name= 'Output', 	value_type= 'set', 		action= 'update_menus', 		},
  {	category= 'Arp', 	sub_category= 'Crow', 	event_type= 'param', 	id= 'arp_ad_skew', 	name= 'AD Skew', 	value_type= 'inc, set', 				},
  {	category= 'Arp', 	sub_category= 'JF', 	event_type= 'param', 	id= 'arp_jf_amp', 	name= 'Amp', 	value_type= 'inc, set', 				},
  {	category= 'Arp', 	sub_category= 'Disting', 	event_type= 'param', 	id= 'arp_disting_velocity', 	name= 'Velocity', 	value_type= 'inc, set', 				},
                      
  -- MIDI harmonizer										
  {	category= 'MIDI harmonizer', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'midi_dest', 	name= 'Destination', 	value_type= 'set', 		action= 'update_menus', 		},
  {	category= 'MIDI harmonizer', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'midi_chord_type', 	name= 'Chord type', 	value_type= 'set', 	formatter= 'chord_type', 			},
  {	category= 'MIDI harmonizer', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'midi_octave', 	name= 'Octave', 	value_type= 'inc, set', 				},
  {	category= 'MIDI harmonizer', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'midi_duration_index', 	name= 'Duration', 	value_type= 'inc, set', 	formatter= 'divisions_string', 	action= 'set_duration', 	action_var= 'midi', 	},
  {	category= 'MIDI harmonizer', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'midi_pp_amp', 	name= 'Amp', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'MIDI harmonizer', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'midi_pp_cutoff', 	name= 'Cutoff', 	value_type= 'inc, set', 				},
  {	category= 'MIDI harmonizer', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'midi_pp_tracking', 	name= 'Fltr tracking', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'MIDI harmonizer', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'midi_pp_gain', 	name= 'Gain', 	value_type= 'inc, set', 				},
  {	category= 'MIDI harmonizer', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'midi_pp_pw', 	name= 'PW', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'MIDI harmonizer', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'midi_in_port', 	name= 'In port', 	value_type= 'inc, set', 				},
  {	category= 'MIDI harmonizer', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'midi_midi_out_port', 	name= 'Out port', 	value_type= 'inc, set', 				},
  {	category= 'MIDI harmonizer', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'midi_midi_ch', 	name= 'Channel', 	value_type= 'inc, set', 				},
  {	category= 'MIDI harmonizer', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'do_midi_velocity_passthru', 	name= 'Pass velocity', 	value_type= 'set', 	formatter= 't_f_string', 	action= 'update_menus', 		},
  {	category= 'MIDI harmonizer', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'midi_midi_velocity', 	name= 'Velocity', 	value_type= 'inc, set', 				},
  {	category= 'MIDI harmonizer', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'midi_midi_cc_1_val', 	name= 'CC Mod', 	value_type= 'inc, set', 	formatter= 'neg_to_off', 			},
  {	category= 'MIDI harmonizer', 	sub_category= 'Crow', 	event_type= 'param', 	id= 'midi_tr_env', 	name= 'Output', 	value_type= 'set', 		action= 'update_menus', 		},
  {	category= 'MIDI harmonizer', 	sub_category= 'Crow', 	event_type= 'param', 	id= 'midi_ad_skew', 	name= 'AD Skew', 	value_type= 'inc, set', 				},
  {	category= 'MIDI harmonizer', 	sub_category= 'JF', 	event_type= 'param', 	id= 'midi_jf_amp', 	name= 'Amp', 	value_type= 'inc, set', 				},
  {	category= 'MIDI harmonizer', 	sub_category= 'Disting', 	event_type= 'param', 	id= 'midi_disting_velocity', 	name= 'Velocity', 	value_type= 'inc, set', 				},
                      
  -- CV harmonizer										
  {	category= 'CV harmonizer', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'crow_dest', 	name= 'Destination', 	value_type= 'set', 		action= 'update_menus', 		},
  {	category= 'CV harmonizer', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'crow_chord_type', 	name= 'Chord type', 	value_type= 'set', 	formatter= 'chord_type', 			},
  {	category= 'CV harmonizer', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'crow_octave', 	name= 'Octave', 	value_type= 'inc, set', 				},
  {	category= 'CV harmonizer', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'crow_duration_index', 	name= 'Duration', 	value_type= 'inc, set', 	formatter= 'divisions_string', 	action= 'set_duration', 	action_var= 'crow', 	},
  {	category= 'CV harmonizer', 	sub_category= 'Voice', 	event_type= 'param', 	id= 'do_crow_auto_rest', 	name= 'Auto-rest', 	value_type= 'set', 	formatter= 't_f_string', 			},
  {	category= 'CV harmonizer', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'crow_pp_amp', 	name= 'Amp', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'CV harmonizer', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'crow_pp_cutoff', 	name= 'Cutoff', 	value_type= 'inc, set', 				},
  {	category= 'CV harmonizer', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'crow_pp_tracking', 	name= 'Fltr tracking', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'CV harmonizer', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'crow_pp_gain', 	name= 'Gain', 	value_type= 'inc, set', 				},
  {	category= 'CV harmonizer', 	sub_category= 'Engine', 	event_type= 'param', 	id= 'crow_pp_pw', 	name= 'PW', 	value_type= 'inc, set', 	formatter= 'percent', 			},
  {	category= 'CV harmonizer', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'crow_midi_out_port', 	name= 'Out port', 	value_type= 'inc, set', 				},
  {	category= 'CV harmonizer', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'crow_midi_ch', 	name= 'Channel', 	value_type= 'inc, set', 				},
  {	category= 'CV harmonizer', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'crow_midi_velocity', 	name= 'Velocity', 	value_type= 'inc, set', 				},
  {	category= 'CV harmonizer', 	sub_category= 'MIDI', 	event_type= 'param', 	id= 'crow_midi_cc_1_val', 	name= 'CC Mod', 	value_type= 'inc, set', 	formatter= 'neg_to_off', 			},
  {	category= 'CV harmonizer', 	sub_category= 'Crow', 	event_type= 'param', 	id= 'crow_tr_env', 	name= 'Output', 	value_type= 'set', 		action= 'update_menus', 		},
  {	category= 'CV harmonizer', 	sub_category= 'Crow', 	event_type= 'param', 	id= 'crow_ad_skew', 	name= 'AD Skew', 	value_type= 'inc, set', 				},
  {	category= 'CV harmonizer', 	sub_category= 'JF', 	event_type= 'param', 	id= 'crow_jf_amp', 	name= 'Amp', 	value_type= 'inc, set', 				},
  {	category= 'CV harmonizer', 	sub_category= 'Disting', 	event_type= 'param', 	id= 'crow_disting_velocity', 	name= 'Velocity', 	value_type= 'inc, set', 				},
  }										