-- Lookup table for events
events_lookup = {
  
  {	category= 'Global', 	event_type= 'param', 	id= 'clock_tempo', 	name= 'Tempo', 	value_type= 'inc, set', 				},
  {	category= 'Global', 	event_type= 'param', 	id= 'transpose', 	name= 'Key', 	value_type= 'inc, set', 	formatter= 'transpose_string', 			},
  {	category= 'Global', 	event_type= 'function', 	id= 'generator', 	name= 'Generate patterns', 	value_type= 'trigger', 				},
  {	category= 'Global', 	event_type= 'param', 	id= 'mode', 	name= 'Mode', 	value_type= 'set', 	formatter= 'mode_index_to_name', 			},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_octave', 	name= 'Chord octave', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_type', 	name= 'Chord type', 	value_type= 'set', 	formatter= 'chord_type', 			},
  {	category= 'Chord', 	event_type= 'function', 	id= 'transpose_chord_pattern', 	name= 'Transpose chord', 	value_type= 'set', 				},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_div_index', 	name= 'Chord step length', 	value_type= 'set', 	formatter= 'divisions_string', 	action= 'set_div', 	action_var= 'chord', 	},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_duration_index', 	name= 'Chord duration', 	value_type= 'inc, set', 	formatter= 'divisions_string', 	action= 'set_duration', 	action_var= 'chord', 	},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_dest', 	name= 'Chord destination', 	value_type= 'set', 		action= 'menu_update', 		},
  {	category= 'Arp', 	event_type= 'function', 	id= 'shuffle_arp', 	name= 'Shuffle Arp', 	value_type= 'trigger', 				},
  {	category= 'Arp', 	event_type= 'function', 	id= 'rotate_arp', 	name= 'Rotate Arp', 	value_type= 'set', 				},
  {	category= 'Arp', 	event_type= 'function', 	id= 'transpose_arp_pattern', 	name= 'Transpose arp', 	value_type= 'set', 				},
  {	category= 'Arp', 	event_type= 'param', 	id= 'arp_octave', 	name= 'Arp octave', 	value_type= 'inc, set', 				},
  {	category= 'Arp', 	event_type= 'param', 	id= 'arp_chord_type', 	name= 'Arp chord type', 	value_type= 'set', 	formatter= 'chord_type', 			},
  {	category= 'Arp', 	event_type= 'param', 	id= 'arp_mode', 	name= 'Arp mode', 	value_type= 'set', 				},
  {	category= 'Arp', 	event_type= 'param', 	id= 'arp_div_index', 	name= 'Arp step length', 	value_type= 'set', 	formatter= 'divisions_string', 	action= 'set_div', 	action_var= 'arp', 	},
  {	category= 'CV', 	event_type= 'function', 	id= 'crow_event_trigger', 	name= 'Trigger to Crow out 4', 	value_type= 'trigger', 				},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_dest', 	name= 'Destination', 	value_type= 'set', 		action= 'menu_update', 		},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_pp_cutoff', 	name= 'Engine cutoff', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_pp_gain', 	name= 'Engine gain', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_pp_pw', 	name= 'Engine PW', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_midi_velocity', 	name= 'MIDI velocity', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_midi_ch', 	name= 'Midi channel', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_jf_amp', 	name= 'Just Friends amp', 	value_type= 'inc, set', 				},
  {	category= 'Chord', 	event_type= 'param', 	id= 'chord_generator', 	name= 'Generator algo', 	value_type= 'inc, set', 				},
  
  }