events_lookup = {										--
-- Global										
{	category= 'Global', 	subcategory= 'Mood', 	event_type= 'param', 	id= 'mode', 	name= 'Mode', 	value_type= 'continuous', 	formatter= 'mode_index_to_name', 			},
{	category= 'Global', 	subcategory= 'Mood', 	event_type= 'param', 	id= 'transpose', 	name= 'Key', 	value_type= 'continuous', 	formatter= 'transpose_string', 			},
{	category= 'Global', 	subcategory= 'Mood', 	event_type= 'param', 	id= 'clock_tempo', 	name= 'Tempo', 	value_type= 'continuous', 				},
{	category= 'Global', 	subcategory= 'Crow out 3', 	event_type= 'param', 	id= 'crow_clock_index', 	name= 'Crow clock', 	value_type= 'continuous', 	formatter= 'crow_clock_string', 			},
{	category= 'Global', 	subcategory= 'Crow out 4', 	event_type= 'function', 	id= 'crow_event_trigger', 	name= 'CV4 trigger out', 	value_type= 'trigger', 				},
{	category= 'Global', 	subcategory= 'Generator', 	event_type= 'param', 	id= 'chord_generator', 	name= 'Chord algo', 	value_type= 'continuous', 				},
{	category= 'Global', 	subcategory= 'Generator', 	event_type= 'param', 	id= 'seq_generator', 	name= 'Seq algo', 	value_type= 'continuous', 				},
{	category= 'Global', 	subcategory= 'Generator', 	event_type= 'function', 	id= 'event_chord_gen', 	name= 'Chord gen', 	value_type= 'trigger', 				},
{	category= 'Global', 	subcategory= 'Generator', 	event_type= 'function', 	id= 'event_seq_gen', 	name= 'Seq gen', 	value_type= 'trigger', 				},
{	category= 'Global', 	subcategory= 'Generator', 	event_type= 'function', 	id= 'event_gen', 	name= 'C+S gen', 	value_type= 'trigger', 				},
-- Chord										
{	category= 'Chord', 	subcategory= 'Pattern', 	event_type= 'param', 	id= 'chord_div_index', 	name= 'Step length', 	value_type= 'continuous', 	formatter= 'divisions_string', 			},
{	category= 'Chord', 	subcategory= 'Pattern', 	event_type= 'param', 	id= 'chord_pattern_length', 	name= 'Pattern length', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'chord_output', 	name= 'Output', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'chord_type', 	name= 'Chord type', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'chord_octave', 	name= 'Octave', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'chord_range', 	name= 'Range', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'chord_max_notes', 	name= 'Max notes', 	value_type= 'continuous', 	formatter= 'max_notes_string', 			},
{	category= 'Chord', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'chord_inversion', 	name= 'Inversion', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'chord_style', 	name= 'Strum', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'chord_strum_length', 	name= 'Strum length', 	value_type= 'continuous', 	formatter= 'strum_length_string', 			},
{	category= 'Chord', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'chord_timing_curve', 	name= 'Strum curve', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'Chord', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'chord_duration_index', 	name= 'Duration', 	value_type= 'continuous', 	formatter= 'divisions_string', 			},
{	category= 'Chord', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'chord_pp_amp', 	name= 'Amp', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'Chord', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'chord_pp_cutoff', 	name= 'Cutoff', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'chord_pp_tracking', 	name= 'Fltr tracking', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'Chord', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'chord_pp_gain', 	name= 'Gain', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'chord_pp_pw', 	name= 'PW', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'Chord', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'chord_midi_out_port', 	name= 'Out port', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'chord_midi_ch', 	name= 'Channel', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'chord_midi_velocity', 	name= 'Velocity', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'chord_midi_cc_1_val', 	name= 'CC Mod', 	value_type= 'continuous', 	formatter= 'neg_to_off', 			},
{	category= 'Chord', 	subcategory= 'Crow', 	event_type= 'param', 	id= 'chord_tr_env', 	name= 'Output', 	value_type= 'continuous', 				},
{	category= 'Chord', 	subcategory= 'Crow', 	event_type= 'param', 	id= 'chord_ad_skew', 	name= 'AD Skew', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'Chord', 	subcategory= 'JF', 	event_type= 'param', 	id= 'chord_jf_amp', 	name= 'Amp', 	value_type= 'continuous', 	formatter= 'ten_v', 			},
{	category= 'Chord', 	subcategory= 'Disting', 	event_type= 'param', 	id= 'chord_disting_velocity', 	name= 'Velocity', 	value_type= 'continuous', 	formatter= 'ten_v', 			},
-- Seq										
{	category= 'Seq', 	subcategory= 'Type', 	event_type= 'param', 	id= 'seq_note_map_1', 	name= 'Notes', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Type', 	event_type= 'param', 	id= 'seq_start_on_1', 	name= 'Start on', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Type', 	event_type= 'param', 	id= 'seq_reset_on_1', 	name= 'Reset on', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Type', 	event_type= 'param', 	id= 'seq_start_1', 	name= 'Start', 	value_type= 'trigger', 				},
{	category= 'Seq', 	subcategory= 'Type', 	event_type= 'param', 	id= 'seq_reset_1', 	name= 'Reset', 	value_type= 'trigger', 				},
{	category= 'Seq', 	subcategory= 'Pattern', 	event_type= 'param', 	id= 'seq_div_index_1', 	name= 'Step length', 	value_type= 'continuous', 	formatter= 'divisions_string', 			},
{	category= 'Seq', 	subcategory= 'Pattern', 	event_type= 'param', 	id= 'seq_pattern_length_1', 	name= 'Pattern length', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Pattern', 	event_type= 'param', 	id= 'seq_rotate_1', 	name= 'Pattern rotate', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Pattern', 	event_type= 'param', 	id= 'seq_shift_1', 	name= 'Pattern shift', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Pattern', 	event_type= 'function', 	id= 'shuffle_seq_1', 	name= 'Shuffle', 	value_type= 'trigger', 				},
{	category= 'Seq', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'seq_output_1', 	name= 'Output', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'seq_octave_1', 	name= 'Octave', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'seq_duration_index_1', 	name= 'Duration', 	value_type= 'continuous', 	formatter= 'divisions_string', 			},
{	category= 'Seq', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'seq_pp_amp_1', 	name= 'Amp', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'Seq', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'seq_pp_cutoff_1', 	name= 'Cutoff', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'seq_pp_tracking_1', 	name= 'Fltr tracking', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'Seq', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'seq_pp_gain_1', 	name= 'Gain', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'seq_pp_pw_1', 	name= 'PW', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'Seq', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'seq_midi_out_port_1', 	name= 'Out port', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'seq_midi_ch_1', 	name= 'Channel', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'seq_midi_velocity_1', 	name= 'Velocity', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'seq_midi_cc_1_val_1', 	name= 'CC Mod', 	value_type= 'continuous', 	formatter= 'neg_to_off', 			},
{	category= 'Seq', 	subcategory= 'Crow', 	event_type= 'param', 	id= 'seq_tr_env_1', 	name= 'Output', 	value_type= 'continuous', 				},
{	category= 'Seq', 	subcategory= 'Crow', 	event_type= 'param', 	id= 'seq_ad_skew_1', 	name= 'AD Skew', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'Seq', 	subcategory= 'JF', 	event_type= 'param', 	id= 'seq_jf_amp_1', 	name= 'Amp', 	value_type= 'continuous', 	formatter= 'ten_v', 			},
{	category= 'Seq', 	subcategory= 'Disting', 	event_type= 'param', 	id= 'seq_disting_velocity_1', 	name= 'Velocity', 	value_type= 'continuous', 	formatter= 'ten_v', 			},
-- MIDI harmonizer										
{	category= 'MIDI harmonizer', 	subcategory= 'Type', 	event_type= 'param', 	id= 'midi_note_map', 	name= 'Notes', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'midi_output', 	name= 'Output', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'midi_octave', 	name= 'Octave', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'midi_duration_index', 	name= 'Duration', 	value_type= 'continuous', 	formatter= 'divisions_string', 			},
{	category= 'MIDI harmonizer', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'midi_pp_amp', 	name= 'Amp', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'MIDI harmonizer', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'midi_pp_cutoff', 	name= 'Cutoff', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'midi_pp_tracking', 	name= 'Fltr tracking', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'MIDI harmonizer', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'midi_pp_gain', 	name= 'Gain', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'midi_pp_pw', 	name= 'PW', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'MIDI harmonizer', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'midi_harmonizer_in_port', 	name= 'In port', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'midi_midi_out_port', 	name= 'Out port', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'midi_midi_ch', 	name= 'Channel', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'midi_velocity_passthru', 	name= 'Pass velocity', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'midi_midi_velocity', 	name= 'Velocity', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'midi_midi_cc_1_val', 	name= 'CC Mod', 	value_type= 'continuous', 	formatter= 'neg_to_off', 			},
{	category= 'MIDI harmonizer', 	subcategory= 'Crow', 	event_type= 'param', 	id= 'midi_tr_env', 	name= 'Output', 	value_type= 'continuous', 				},
{	category= 'MIDI harmonizer', 	subcategory= 'Crow', 	event_type= 'param', 	id= 'midi_ad_skew', 	name= 'AD Skew', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'MIDI harmonizer', 	subcategory= 'JF', 	event_type= 'param', 	id= 'midi_jf_amp', 	name= 'Amp', 	value_type= 'continuous', 	formatter= 'ten_v', 			},
{	category= 'MIDI harmonizer', 	subcategory= 'Disting', 	event_type= 'param', 	id= 'midi_disting_velocity', 	name= 'Velocity', 	value_type= 'continuous', 	formatter= 'ten_v', 			},
-- CV harmonizer										
{	category= 'CV harmonizer', 	subcategory= 'Type', 	event_type= 'param', 	id= 'crow_note_map', 	name= 'Notes', 	value_type= 'continuous', 				},
{	category= 'CV harmonizer', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'crow_output', 	name= 'Output', 	value_type= 'continuous', 				},
{	category= 'CV harmonizer', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'crow_octave', 	name= 'Octave', 	value_type= 'continuous', 				},
{	category= 'CV harmonizer', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'crow_duration_index', 	name= 'Duration', 	value_type= 'continuous', 	formatter= 'divisions_string', 			},
{	category= 'CV harmonizer', 	subcategory= 'Voice', 	event_type= 'param', 	id= 'crow_auto_rest', 	name= 'Auto-rest', 	value_type= 'continuous', 				},
{	category= 'CV harmonizer', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'crow_pp_amp', 	name= 'Amp', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'CV harmonizer', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'crow_pp_cutoff', 	name= 'Cutoff', 	value_type= 'continuous', 				},
{	category= 'CV harmonizer', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'crow_pp_tracking', 	name= 'Fltr tracking', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'CV harmonizer', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'crow_pp_gain', 	name= 'Gain', 	value_type= 'continuous', 				},
{	category= 'CV harmonizer', 	subcategory= 'Engine', 	event_type= 'param', 	id= 'crow_pp_pw', 	name= 'PW', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'CV harmonizer', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'crow_midi_out_port', 	name= 'Out port', 	value_type= 'continuous', 				},
{	category= 'CV harmonizer', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'crow_midi_ch', 	name= 'Channel', 	value_type= 'continuous', 				},
{	category= 'CV harmonizer', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'crow_midi_velocity', 	name= 'Velocity', 	value_type= 'continuous', 				},
{	category= 'CV harmonizer', 	subcategory= 'MIDI', 	event_type= 'param', 	id= 'crow_midi_cc_1_val', 	name= 'CC Mod', 	value_type= 'continuous', 	formatter= 'neg_to_off', 			},
{	category= 'CV harmonizer', 	subcategory= 'Crow', 	event_type= 'param', 	id= 'crow_tr_env', 	name= 'Output', 	value_type= 'continuous', 				},
{	category= 'CV harmonizer', 	subcategory= 'Crow', 	event_type= 'param', 	id= 'crow_ad_skew', 	name= 'AD Skew', 	value_type= 'continuous', 	formatter= 'percent', 			},
{	category= 'CV harmonizer', 	subcategory= 'JF', 	event_type= 'param', 	id= 'crow_jf_amp', 	name= 'Amp', 	value_type= 'continuous', 	formatter= 'ten_v', 			},
{	category= 'CV harmonizer', 	subcategory= 'Disting', 	event_type= 'param', 	id= 'crow_disting_velocity', 	name= 'Velocity', 	value_type= 'continuous', 	formatter= 'ten_v', 			},
}										-- end